[package]
name = "mfgj2023"
version = "0.1.0"
edition = "2021"

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = { version ="0.11.0", features = ["dynamic_linking"]} # TODO: remove in release
